image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - code_quality
  - test
  - build
  - develop
  - production

code_quality:
  image: ubuntu:latest
  stage: code_quality
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the main branch only.
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization: Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" + -H "username: elizabeth.james@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$CI_PIPELINE_IID&project_name=wiseshopping" -F "file=@Designite_output/DesigniteAnalysis.xml"'
  before_script:
    - apt-get update
    - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
    - apt-get --yes --force-yes install wget curl maven git
  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - java --version
    - echo $CI_PROJECT_PATH
    - java -jar 'DesigniteJava.jar' -ci -repo $CI_PROJECT_PATH -pat $PAT -host "git.cs.dal.ca"
    #- java -jar DesigniteJava.jar -i . -o Designite_output -f XML
    - 'eval "$UPLOAD_QUALITY_REPORT"'

# test stage will compile the code and run all the unit tests present in the
# test folder.
test:
  stage: test
  tags:
    - ugrad
  script:
    - mvn clean test

# build stage will just build the codebase without running
# any tests or creating any jar file.
build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean install -DskipTests=true
    - ls
  artifacts:
    paths:
      - target/*.jar


## deploy stage will create package the jar and keep it in the target folder.
## The success of deploy stage will mark the pipeline as passed.
develop:
  stage: develop
  tags:
    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "dbURL=$DATABASE_URL" > config.properties
    - echo "dbUserName=$TEST_DATABASE_USERNAME" >> config.properties
    - echo "dbPassword=$TEST_DATABASE_PASSWORD" >> config.properties
    - echo "dbDriver=$TEST_DATABASE" >> config.properties
    - pwd
    - ls -lrth
    - ls target/
    - ls -lrth ~/.ssh
    - echo "$CI_COMMIT_REF_NAME"
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip . -i target/*.jar
    - ls -lrth ${CI_COMMIT_SHORT_SHA}.zip
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - scp -r -o StrictHostKeyChecking=no config.properties "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/config.properties"
  only:
    - dev


production:
  stage: production
  tags:
    - ugrad
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "dbURL=$DATABASE_URL" > config.properties
    - echo "dbUserName=$PROD_DATABASE_USERNAME" >> config.properties
    - echo "dbPassword=$PROD_DATABASE_PASSWORD" >> config.properties
    - echo "dbDriver=$PROD_DATABASE" >> config.properties
    - pwd
    - ls -lrth
    - ls target/
    - ls -lrth ~/.ssh
    - echo "$CI_COMMIT_REF_NAME"
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip . -i target/*.jar
    - ls -lrth ${CI_COMMIT_SHORT_SHA}.zip
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${PROD_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
    - scp -r -o StrictHostKeyChecking=no config.properties "${DEPLOY_USER}@${DEPLOY_HOST}:${PROD_DIR}/config.properties"
  only:
    - main
